# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'finance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfinance.proto\x12\x07\x66inance\"#\n\x11GetSummaryRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"?\n\x12GetSummaryResponse\x12\x13\n\x0btotalIncome\x18\x01 \x01(\x01\x12\x14\n\x0ctotalExpense\x18\x02 \x01(\x01\"#\n\x11GetHistoryRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"l\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"W\n\x15\x41\x64\x64TransactionRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\":\n\x16\x41\x64\x64TransactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf2\x01\n\x0e\x46inanceService\x12G\n\nGetSummary\x12\x1a.finance.GetSummaryRequest\x1a\x1b.finance.GetSummaryResponse\"\x00\x12\x42\n\nGetHistory\x12\x1a.finance.GetHistoryRequest\x1a\x14.finance.Transaction\"\x00\x30\x01\x12S\n\x0e\x41\x64\x64Transaction\x12\x1e.finance.AddTransactionRequest\x1a\x1f.finance.AddTransactionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSUMMARYREQUEST']._serialized_start=26
  _globals['_GETSUMMARYREQUEST']._serialized_end=61
  _globals['_GETSUMMARYRESPONSE']._serialized_start=63
  _globals['_GETSUMMARYRESPONSE']._serialized_end=126
  _globals['_GETHISTORYREQUEST']._serialized_start=128
  _globals['_GETHISTORYREQUEST']._serialized_end=163
  _globals['_TRANSACTION']._serialized_start=165
  _globals['_TRANSACTION']._serialized_end=273
  _globals['_ADDTRANSACTIONREQUEST']._serialized_start=275
  _globals['_ADDTRANSACTIONREQUEST']._serialized_end=362
  _globals['_ADDTRANSACTIONRESPONSE']._serialized_start=364
  _globals['_ADDTRANSACTIONRESPONSE']._serialized_end=422
  _globals['_FINANCESERVICE']._serialized_start=425
  _globals['_FINANCESERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
